[project]
name = "competitive-programing"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "mei", email = "mei28aquarius@gmail.com" }
]
dependencies = [
    "numpy==1.24.1",
    "scipy==1.10.1",
    "scikit-learn==1.2.0",
    "polars==0.15.15",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true
